### ISSUE TITLE
updates

### ISSUE THREAD

**Issue by kosoegawa** [nmdp-bioinformatics/ImmunogeneticDataTools#12]
Could I updates the program in my server?
Also, could you tell me how to test? IS there any specific file name for testing?

**Comment by mpresteg** [comment]
I had updated the README.md and the Wiki with instructions about how to test.

Given that you've already done your basic set up.  Your steps should be:
- git pull
- mvn compile package
- mvn exec:java -Dexec.mainClass="org.dash.valid.LinkageDisequilibriumLoader" -Dexec.args="resources/test/stanfordExamples.txt"

That will run the test examples provided at DaSH.

Output will be in a file called linkages.log (which will likely default to your home directory, dependent upon your local set up).

In my last email, I had sent output from that test set.  The code base I used at that time, should be the same as what is currently pushed to GitHub.

If your interest is to test individual GL Strings, where you control the input (rather than the large test set), I'll need to provide slightly different instructions.

**Comment by kosoegawa** [comment]
When I execute "git pull", I got the following message:
error: Your local changes to 'resources/test/contrivedExamples.txt' would be ove                      rwritten by merge.  Aborting.
Please, commit your changes or stash them before you can merge.
Do you how to fix this?

**Comment by mpresteg** [comment]
I assume you have no interest in your local changes.  I manage merges using Eclipse, so I haven't tried it via command line.  Some poking around on the internet suggests the following.  Be aware it will toss any local changes you have (which I think is the intent here):
git fetch --all
git reset --hard origin/master
git pull origin master

**Comment by kosoegawa** [comment]
I think the problem was that I modified contrivedExamples.txt for my test. I could not fix the error message, so I deleted contrivedExamples.txt from the test directory. When I execute 'git pull', I did not see error message, and copied the original contrivedExamples.txt. It should work now.
